### ISSUE TITLE
CI from pull request did not update the site properly

### ISSUE THREAD

**Issue by doctor-g** [spring2017gamestudio/prairie-creek#11]
Right after [the new software architecture was merged into `master`](https://github.com/spring2017gamestudio/prairie-creek/commit/004f862e1d0986aa5b05835bfd1df9fb44c0ff26), I checked [the CI build](https://spring2017gamestudio.github.io/prairie-creek/) and found that it was not loading. Upon investigation, I discovered that all the new elements were missing from the deployed game. [The log for this build](https://travis-ci.org/spring2017gamestudio/prairie-creek/builds/201333304) shows that some files were deleted from `gh-pages` but the new ones were not actually pushed until [the next commit](https://travis-ci.org/spring2017gamestudio/prairie-creek/builds/201364024), when I fixed a typo in the `polymer.json` file. I don't think that typo was related to the CI failure, although I don't dismiss the possibility. 

We will have to watch the CI build the next time a PR is merged and ensure that the changes show up live, and if not, figure out what's wrong with the build script.

**Comment by dakotamalchow** [comment]
We also saw this with our most recent commit for data format with hot-spot-id:

https://github.com/spring2017gamestudio/prairie-creek/commit/3a3574e9485d8f99cb3d1edd208a0a39e49fa90f
