### ISSUE TITLE
Checkboxes pre-selected to match previous site's selections

### ISSUE THREAD

**Issue by doctor-g** [spring2017gamestudio/prairie-creek#27]
To reproduce, go to a site and make some selections. The next site you go to, the corresponding items (by index) will be selected.

**Comment by zmbube** [comment]
An interesting interaction I have noticed is that the checkboxes are only checked if you switch directly from site to site. If you travel to a point where currentSite becomes undefined and then to a new site the checkboxes are all unchecked.

**Comment by doctor-g** [comment]
@zmbube That is interesting, since we generally expect the locations not to overlap... but I suppose in theory they could. So I don't think it's just a "developer mode" error, even though it wouldn't show up in the wild in the BSU version.

**Comment by grevers** [comment]
Hey I solved this issue in the current build by binding the checked attribute to item.selected.
<paper-checkbox
        class="checkbox"
        index="[[index]]"
        item="[[item]]"
        **checked$="[[item.selected]]"**
        on-tap="_onCheckboxTap">
          [[item.text]]
      </paper-checkbox>

**Comment by doctor-g** [comment]
@grevers is that part of the `debug-mode` branch? We looked at that branch, and I think it has much too many things going on in it. Because it was based on `master` before the merges of this morning, we were planning to just abandon it as we go in our different direction. Do you want to take this approach and try it off of the current master? There are so many changes to `checklist-view`, it's important we make sure the approach jives with them, and the tests of the same.

**Comment by grevers** [comment]
@doctor-g The change I'm proposing is based on the current master. The debug-mode branch got out of hand.

**Comment by doctor-g** [comment]
@grevers Is it on a feature branch? The change sounds good if the tests pass, may be able to simplify the implementation even. Tag me when it becomes a PR, I'd like to take a look.

**Comment by grevers** [comment]
@doctor-g I'll put it on a branch and make a PR.

**Comment by grevers** [comment]
This issue was fixed by pull request #33
