### ISSUE TITLE
Default Location 0°N 0°E

### ISSUE THREAD

**Issue by grevers** [spring2017gamestudio/prairie-creek#48]
If a user has disabled their GPS there location is displayed as 0°N 0°E or where the equator crosses the prime meridian.

The issue can be reproduced in chrome by [accessing sensor controls](https://developers.google.com/web/tools/chrome-devtools/device-mode/device-input-and-sensors), and setting Geolocation to **Error** Location unavailable.

**Comment by doctor-g** [comment]
How did this go yesterday, @grevers? Is there a feature branch with your progress on it, or is it something someone else with some spare cycles could dig into?

**Comment by grevers** [comment]
@doctor-g let me slap it in a branch. It went a lot smoother when I started fresh.
