### ISSUE TITLE
Small Location Arrival Radius

### ISSUE THREAD

**Issue by grevers** [spring2017gamestudio/prairie-creek#71]
The ring around bell tower and CAP is small and makes arriving at a location tedious. The CAP building center may need to be moved.

**Comment by doctor-g** [comment]
This issue relates to an easily-modified value in the code. However, we have also talked about a separate problem, which is that standing on the edge of a radius may cause throttling between two zones. I propose we split these into two issues. What do you think, @grevers?

**Comment by grevers** [comment]
I think the issue of jumping in and out is separate from this. I believe this issue was closed by #84.
