### ISSUE TITLE
Only get Neutral Spirit on Browsers besides chrome

### ISSUE THREAD

**Issue by zmbube** [spring2017gamestudio/prairie-creek#72]
The spirit view always resolves to displaying the neutral spirit on all browsers except for chrome.

**Comment by zmbube** [comment]
I believe this is related to an issue with paper-checkbox in the checklist view. The issue is mentioned here https://github.com/PolymerElements/paper-checkbox/issues/170

**Comment by zmbube** [comment]
@doctor-g after following your suggestions and fiddling around with it a bit i discovered the problem is coming from the event.target call.  In firefox the compiled page has sub parts to the checkbox like the container and the label and returns these rather than the whole checkbox where the index and checked properties are.
![screen shot 2017-03-29 at 1 43 44 pm](https://cloud.githubusercontent.com/assets/13968759/24468334/dff8960e-1485-11e7-8733-cfaf0bbba24e.png)

**Comment by doctor-g** [comment]
@zmbube It's a little unclear to me from what you said above. Can you clarify, what is `event.target` returning in Chrome and Firefox? [This line](https://github.com/spring2017gamestudio/prairie-creek/blob/master/src/checklist-view/checklist-view.html#L44) is returning something different from each? 

Looking at the code, I see that the local variable `item` is never used, so it can be cut.

**Comment by zmbube** [comment]
In Firefox and Safari even is returning the div checkboxContainer or checkboxLabel from the picture above depending on if you click the text or the box. Chrome returns the paper-checkbox itself no matter where you click.

**Comment by doctor-g** [comment]
Aha, I see. I put a `debugger` call in the [`onCheckboxTap`](https://github.com/spring2017gamestudio/prairie-creek/blob/master/src/checklist-view/checklist-view.html#L44) method, and then went into the console and evaluated `event.target` in each. Chrome gives you the paper-checkbox that has a valid `checked` property; Firefox does not.

**Comment by doctor-g** [comment]
@zmbube Try using `event.currentTarget` instead and see if that helps.

It would also be great to have a unit test to reproduce this in fewer steps.
